"""Command line interface.

Each command is one step of the cycle:

    import -> diagnose -> profile -> strategy -> calendar
           -> post -> publish -> metrics -> (back to strategy)

Run `uv run linkedin --help` to see everything.
"""

from __future__ import annotations

import csv
import re
from datetime import date
from pathlib import Path
from typing import Annotated, Optional

import typer
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

from linkedin_growth.config import (
    CONTENT_DIR,
    DEFAULT_SESSION,
    EXPORT_DIR,
    MAX_TOKENS,
    METRICS_CSV,
    POSTS_DIR,
    PROFILE_YAML,
    MissingConfiguration,
    ensure_directories,
)

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="LinkedIn relevance system for AI engineering.",
)
console = Console()


# ==============================================================================
# Helpers
# ==============================================================================


def _fail(message: str) -> None:
    console.print(Panel(message, title="Error", border_style="red"))
    raise typer.Exit(code=1)


def _warn_if_truncated(output) -> None:
    """Warn when the response hit the `max_tokens` ceiling.

    This cost us once already: the agent wrote the entire report, the response
    was cut exactly at the limit, the `save_artifact` call never happened, and
    the text on screen ended with "report saved". Nothing signalled the failure.
    The ceiling was raised in `config.MAX_TOKENS`, but the failure mode still
    exists, and it is invisible by nature: the user only finds out when they go
    looking for the file.

    Agno does not expose the provider's `stop_reason`, so the signal used here
    is the last message's spend hitting the ceiling.
    """
    last = next(
        (
            message
            for message in reversed(output.messages or [])
            if message.role == "assistant"
        ),
        None,
    )
    spend = getattr(last, "metrics", None)
    if not spend or (spend.output_tokens or 0) < MAX_TOKENS:
        return

    console.print(
        Panel(
            "The response was cut at the token limit, so the ending was lost, "
            "including any file write.\n\n"
            "Check whether the artifact was created. To give it more room, "
            "raise this in .env:\n"
            f"    MAX_TOKENS={MAX_TOKENS * 2}",
            title="Response truncated",
            border_style="yellow",
        )
    )


def _run_agent(build, question: str, title: str) -> None:
    """Run an agent, handling approval pauses."""
    ensure_directories()
    try:
        agent = build()
    except MissingConfiguration as error:
        _fail(str(error))

    console.rule(f"[bold]{title}")
    output = agent.run(question)

    while output.is_paused:
        for pending in output.tools_requiring_confirmation:
            console.print(
                Panel(
                    f"[bold]{pending.tool_name}[/bold]\n\n{pending.tool_args}",
                    title="Approval required",
                    border_style="yellow",
                )
            )
            pending.confirmed = Confirm.ask("Run it?", default=False)
        output = agent.continue_run(run_response=output)

    if output.content:
        console.print(Markdown(str(output.content)))
    _warn_if_truncated(output)


def _extract_section(text: str, language: str) -> Optional[str]:
    """Pull the post body out from under the requested version's heading.

    The heading comes from `principles.POST_HEADING`, the same constant the
    Editor receives in its instructions. Both ends of the contract come from one
    source, otherwise they drift apart silently and `publish` breaks only at the
    worst moment.

    The regex is deliberately forgiving about what does not matter: the file is
    generated by a model, so we accept one to three '#', spacing variation and
    the optional country suffix. It stops at the next heading of any level.
    """
    from linkedin_growth.agents.principles import POST_HEADING

    heading = POST_HEADING.get(language)
    if not heading:
        return None

    label = re.escape(heading.lstrip("# ").strip())
    # 'Post (pt-BR)' -> 'Post \( pt (-BR)? \)', so '(pt)' and '(pt-BR)' both hit.
    label = label.replace(r"\-BR", r"(?:\-BR)?").replace(r"\(en\)", r"\(en(?:\-US)?\)")
    found = re.search(
        rf"^#{{1,3}}\s*{label}\s*$\n(.*?)(?=^#{{1,3}}\s|\Z)",
        text,
        re.DOTALL | re.IGNORECASE | re.MULTILINE,
    )
    return found.group(1).strip() if found else None


# ==============================================================================
# Commands
# ==============================================================================


@app.command("import")
def import_data() -> None:
    """Read the LinkedIn data export and build profile/profile.yaml."""
    from linkedin_growth.profile import importer

    ensure_directories()
    console.rule("[bold]Importing the LinkedIn export")
    console.print(f"Reading from: [cyan]{EXPORT_DIR}[/cyan]\n")

    profile, report = importer.import_profile()

    if report.files_found:
        table = Table("File recognized", "Items")
        for entry in report.files_found:
            label = entry.split("(")[-1].rstrip(")")
            table.add_row(entry, str(report.counts.get(label, "-")))
        console.print(table)

    if report.files_ignored:
        console.print(
            f"\n[dim]Ignored ({len(report.files_ignored)}): "
            f"{', '.join(report.files_ignored[:12])}"
            f"{' ...' if len(report.files_ignored) > 12 else ''}[/dim]"
        )

    for warning in report.warnings:
        console.print(f"\n[yellow]Heads up:[/yellow] {warning}")

    if not report.files_found:
        console.print(
            Panel(
                "No known CSV was found.\n\n"
                "1. On LinkedIn: Settings > Data privacy > Get a copy of your "
                "data\n"
                "2. Request the complete archive and wait for the email\n"
                f"3. Unzip it into:\n   {EXPORT_DIR}\n"
                "4. Run this command again",
                title="How to get the export",
                border_style="yellow",
            )
        )
        raise typer.Exit(code=1)

    path = importer.save(profile)
    voice = importer.save_voice(profile)

    console.print(f"\n[green]Profile written to[/green] {path}")
    if voice:
        console.print(
            f"[green]Writing samples in[/green] {voice} "
            f"({len(profile.past_posts)} posts)"
        )
    console.print(
        "\n[bold]Now open profile.yaml and review it.[/bold] Fix what the "
        "importer missed and fill in 'goal' in your own words. That is what "
        "every agent reads."
    )


@app.command()
def diagnose() -> None:
    """Audit your profile against real AI engineering job posts."""
    from linkedin_growth.agents import diagnosis

    _run_agent(
        diagnosis.build,
        "Faça o diagnóstico completo do meu perfil do LinkedIn para uma "
        "transição para engenharia de IA. Pesquise vagas reais primeiro.",
        "Profile diagnosis",
    )


@app.command()
def profile() -> None:
    """Generate headline, About, experiences and projects, ready to paste."""
    from linkedin_growth.agents import profile_writer

    _run_agent(
        profile_writer.build,
        "Escreva a versão otimizada do meu perfil do LinkedIn: headline, "
        "Sobre, experiências, projetos e skills. Português e inglês.",
        "Profile copy",
    )


@app.command()
def strategy() -> None:
    """Define positioning, content pillars and cadence."""
    from linkedin_growth.agents import strategist

    _run_agent(
        strategist.build,
        "Monte a minha estratégia de conteúdo no LinkedIn para os próximos "
        "seis meses, com foco em ser notado por recrutadores de engenharia "
        "de IA.",
        "Content strategy",
    )


@app.command()
def calendar(
    weeks: Annotated[int, typer.Option(help="How many weeks to plan.")] = 2,
) -> None:
    """Build the editorial calendar for the coming weeks."""
    from linkedin_growth import flows

    ensure_directories()
    console.rule("[bold]Editorial calendar")
    try:
        flow = flows.week_flow()
    except MissingConfiguration as error:
        _fail(str(error))

    output = flow.run(
        f"Levante as pautas de engenharia de IA desta semana e monte o "
        f"calendário editorial das próximas {weeks} semanas."
    )
    console.print(Markdown(str(output.content or "")))


@app.command()
def post(
    topic: Annotated[str, typer.Option(help="Topic of the post.")],
) -> None:
    """Research, write (pt + en), review and save a post."""
    from linkedin_growth import flows

    ensure_directories()
    console.rule(f"[bold]Producing post: {topic}")
    try:
        flow = flows.post_flow()
    except MissingConfiguration as error:
        _fail(str(error))

    output = flow.run(topic)
    console.print(Markdown(str(output.content or "")))


@app.command()
def publish(
    file: Annotated[Path, typer.Argument(help="Post file in content/posts/.")],
    language: Annotated[
        str, typer.Option(help="Which version to publish: pt or en.")
    ] = "pt",
    dry_run: Annotated[
        bool, typer.Option("--dry-run", help="Show what would be sent, without sending.")
    ] = False,
) -> None:
    """Publish a post to LinkedIn through the official API."""
    from linkedin_growth.tools import linkedin as li

    path = file if file.is_absolute() else (Path.cwd() / file)
    if not path.exists():
        path = POSTS_DIR / file.name
    if not path.exists():
        _fail(f"File not found: {file}")

    raw = path.read_text(encoding="utf-8")

    # The Editor rejects a post that claims experience the user does not have,
    # and when it does that it deliberately omits the publishable headings so
    # the cut finds no text. Without this check the user would get "could not
    # find the 'pt' section" and go hunting for a format bug that does not
    # exist. The right answer is that the post was rejected, and why.
    if re.search(r"^status:\s*rejected\s*$", raw, re.MULTILINE):
        _fail(
            f"{path.name} was rejected by the Editor and cannot be published.\n\n"
            "The reason is in the file itself, under the evaluation section. "
            "Usually the post claims something your real data does not "
            "support.\n\n"
            "Resolve the open items listed there and regenerate with\n"
            '    uv run linkedin post --topic "..."'
        )

    body = _extract_section(raw, language)
    if not body:
        from linkedin_growth.agents.principles import POST_HEADING

        _fail(
            f"Could not find the '{language}' section in {path.name}.\n"
            f"The file needs a '{POST_HEADING['pt']}' or "
            f"'{POST_HEADING['en']}' heading.\n"
            "If the post came from an older version, run "
            '`uv run linkedin post --topic "..."` again.'
        )

    if "[PREENCHER" in body:
        _fail(
            "The post still has [PREENCHER] markers. Complete the text before "
            "publishing."
        )

    console.print(
        Panel(body, title=f"{path.name} - {language} ({len(body)} characters)")
    )

    if dry_run:
        console.rule("[bold]Dry run (nothing was sent)")
        try:
            console.print(li.preview(body))
        except MissingConfiguration as error:
            _fail(str(error))
        return

    if not Confirm.ask(
        "\n[bold red]Publish this to your LinkedIn now?[/bold red]", default=False
    ):
        console.print("Cancelled.")
        return

    try:
        result = li.publish(body)
    except MissingConfiguration as error:
        _fail(str(error))
    except Exception as error:  # noqa: BLE001 - the failure has to reach the user
        _fail(f"Failed to publish: {error}")

    if result.get("ok"):
        console.print(f"\n[green]Published.[/green] {result['url']}")
        console.print(f"[dim]via {result['endpoint']}[/dim]")
        console.print(
            "\nIn a few days, record the metrics with "
            "[cyan]uv run linkedin metrics[/cyan]."
        )
    else:
        _fail(
            f"LinkedIn refused (HTTP {result.get('status')}):\n"
            f"{result.get('error')}"
        )


@app.command()
def connection() -> None:
    """Check whether the LinkedIn token is still valid."""
    from linkedin_growth.tools import linkedin as li

    try:
        data = li.token_profile()
    except MissingConfiguration as error:
        _fail(str(error))
    except Exception as error:  # noqa: BLE001
        _fail(
            f"Could not reach LinkedIn: {error}\n\n"
            "Tokens last 60 days. Generate another at\n"
            "https://www.linkedin.com/developers/tools/oauth/token-generator"
        )

    console.print(
        Panel(
            f"Connected as [bold]{data.get('name')}[/bold]\n"
            f"urn:li:person:{data.get('sub')}",
            title="LinkedIn",
            border_style="green",
        )
    )


@app.command()
def metrics() -> None:
    """Record the metrics of a published post.

    LinkedIn does not expose post metrics through the self-serve API, so these
    numbers go in by hand. This is what closes the loop: the strategist reads
    this file to learn which kind of post works for you.
    """
    ensure_directories()
    columns = [
        "date",
        "file",
        "pillar",
        "impressions",
        "reactions",
        "comments",
        "profile_views",
        "recruiter_contacts",
        "note",
    ]

    is_new = not METRICS_CSV.exists()
    console.rule("[bold]Record the metrics of a post")

    row = {
        "date": Prompt.ask("Post date", default=date.today().isoformat()),
        "file": Prompt.ask("Post file", default=""),
        "pillar": Prompt.ask("Pillar (built/broke/understood/read/compared)", default=""),
        "impressions": Prompt.ask("Impressions", default="0"),
        "reactions": Prompt.ask("Reactions", default="0"),
        "comments": Prompt.ask("Comments", default="0"),
        "profile_views": Prompt.ask("Profile views this week", default="0"),
        "recruiter_contacts": Prompt.ask("Recruiter contacts", default="0"),
        "note": Prompt.ask("Note", default=""),
    }

    with METRICS_CSV.open("a", encoding="utf-8", newline="") as handle:
        csv_writer = csv.DictWriter(handle, fieldnames=columns)
        if is_new:
            csv_writer.writeheader()
        csv_writer.writerow(row)

    console.print(f"\n[green]Recorded in[/green] {METRICS_CSV}")


@app.command()
def chat(
    session: Annotated[
        str,
        typer.Option(help="Which conversation to continue. Sessions do not mix."),
    ] = DEFAULT_SESSION,
) -> None:
    """Talk to the team in the terminal, picking up where you left off."""
    from linkedin_growth import team

    ensure_directories()
    try:
        crew = team.build(session)
    except MissingConfiguration as error:
        _fail(str(error))

    console.rule("[bold]LinkedIn Presence Team")
    console.print(
        f"[dim]Conversation '[cyan]{session}[/cyan]'. Type 'exit' to quit.[/dim]\n"
    )

    while True:
        try:
            question = Prompt.ask("[bold cyan]you[/bold cyan]")
        except (KeyboardInterrupt, EOFError):
            break
        if question.strip().lower() in {"sair", "exit", "quit"}:
            break
        if not question.strip():
            continue

        output = crew.run(question)

        # Publishing and other sensitive actions pause the run waiting for a yes.
        while output.is_paused:
            for requirement in output.active_requirements:
                if not requirement.needs_confirmation:
                    continue
                execution = requirement.tool_execution
                console.print(
                    Panel(
                        f"[bold]{execution.tool_name}[/bold]\n\n{execution.tool_args}",
                        title="Approval required",
                        border_style="yellow",
                    )
                )
                if Confirm.ask("Run it?", default=False):
                    requirement.confirm()
                else:
                    requirement.reject("The user declined.")
            output = crew.continue_run(run_response=output)

        console.print(Markdown(str(output.content or "")))
        console.print()


@app.command()
def memory(
    forget: Annotated[
        Optional[str],
        typer.Option(help="Delete one memory by the id shown in the listing."),
    ] = None,
    clear: Annotated[
        bool, typer.Option("--clear", help="Delete everything the system remembers.")
    ] = False,
) -> None:
    """Show what the system learned about you in conversation.

    Memory you cannot inspect is memory you cannot trust: if an agent starts
    repeating nonsense, this is where you find out where it came from, and this
    is where you delete it.
    """
    from linkedin_growth.config import USER_ID, memory as memory_manager

    ensure_directories()
    try:
        manager = memory_manager()
    except MissingConfiguration as error:
        _fail(str(error))

    if clear:
        if not Confirm.ask(
            "\n[bold red]Delete EVERYTHING the system remembers about you?[/bold red]",
            default=False,
        ):
            console.print("Cancelled.")
            return
        manager.clear_user_memories(user_id=USER_ID)
        console.print("[green]Memory cleared.[/green]")
        return

    memories = manager.get_user_memories(user_id=USER_ID) or []

    if forget:
        # The table shows the id abbreviated, so the command accepts a prefix.
        matches = [
            entry for entry in memories if (entry.memory_id or "").startswith(forget)
        ]
        if not matches:
            _fail(f"No memory starts with '{forget}'.")
        if len(matches) > 1:
            _fail(
                f"'{forget}' matches {len(matches)} memories. Use more "
                "characters of the id."
            )
        manager.delete_user_memory(memory_id=matches[0].memory_id, user_id=USER_ID)
        console.print(f"[green]Forgotten:[/green] {matches[0].memory}")
        return

    if not memories:
        console.print(
            Panel(
                "The system does not remember anything yet.\n\n"
                "Memory is written while talking to the team:\n"
                "  [cyan]uv run linkedin chat[/cyan]\n\n"
                "Tell it what you prefer, what you built and what worked. "
                "Whatever is worth keeping shows up here.",
                title="Memory is empty",
                border_style="yellow",
            )
        )
        return

    table = Table("id", "what the system remembers", "topics", "when")
    for entry in memories:
        when = entry.updated_at or entry.created_at
        table.add_row(
            (entry.memory_id or "")[:8],
            entry.memory,
            ", ".join(entry.topics or []),
            date.fromtimestamp(when).isoformat() if when else "",
        )
    console.print(table)
    console.print(
        "\n[dim]To delete one: uv run linkedin memory --forget <id>[/dim]"
    )


@app.command()
def serve(
    port: Annotated[int, typer.Option(help="Server port.")] = 7777,
    host: Annotated[str, typer.Option(help="Server host.")] = "localhost",
) -> None:
    """Start AgentOS for the web interface in agent_ui/."""
    try:
        from linkedin_growth.agentos import agent_os, app as fastapi_app
    except MissingConfiguration as error:
        _fail(str(error))

    console.print(
        Panel(
            f"Server at [cyan]http://{host}:{port}[/cyan]\n\n"
            "In another terminal, start the interface:\n"
            "  [cyan]cd agent_ui && pnpm dev[/cyan]\n"
            "and open [cyan]http://localhost:3000[/cyan] in [bold]Team[/bold] mode.",
            title="LinkedIn Growth OS",
            border_style="green",
        )
    )
    agent_os.serve(app=fastapi_app, host=host, port=port)


@app.command()
def status() -> None:
    """Show what already exists and what the next step is."""
    ensure_directories()

    stages = [
        ("profile imported", PROFILE_YAML, "linkedin import"),
        ("diagnosis", CONTENT_DIR / "diagnosis.md", "linkedin diagnose"),
        ("profile copy", CONTENT_DIR / "optimized_profile.md", "linkedin profile"),
        ("strategy", CONTENT_DIR / "strategy.md", "linkedin strategy"),
    ]

    table = Table("Stage", "Status", "Command")
    for label, path, command in stages:
        exists = path.exists()
        table.add_row(
            label,
            "[green]done[/green]" if exists else "[yellow]pending[/yellow]",
            "" if exists else f"uv run {command}",
        )

    posts = list(POSTS_DIR.glob("*.md"))
    calendars = list((CONTENT_DIR / "calendar").glob("*.md"))
    table.add_row("calendars", f"{len(calendars)}", "uv run linkedin calendar")
    table.add_row("posts written", f"{len(posts)}", 'uv run linkedin post --topic "..."')

    console.print(table)


if __name__ == "__main__":
    app()
